name: Build and Deploy Prospero site

on:
  push:
    branches: [ "main" ]           # prod deploys
  pull_request:
    branches: [ "main" ]           # preview deploys for PRs targeting main
  workflow_dispatch:                # manual runs if you want

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate paper pages
        run: npm run build:papers

      - name: Disable Jekyll processing
        run: touch site/.nojekyll

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    name: Deploy to GitHub Pages (prod or preview)
    runs-on: ubuntu-latest
    needs: build
    environment:
      # Keep the special Pages env; GitHub shows the URL on each run
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        # Behavior:
        # - On push to main => production deployment
        # - On pull_request => preview deployment with a unique URL
